version: "3"

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${dbname}'
      - 'POSTGRES_USER=$${spring.datasource.username}'
      - 'POSTGRES_PASSWORD=$${spring.datasource.password}'
    ports:
      - '5432:5432'