global:
  scrape_interval:     10s
  external_labels:
    monitor: saga-flow

scrape_configs:
  - job_name: saga-flow
    scrape_interval: 10s
    static_configs:
      - targets: [host.docker.internal:8080]


  - job_name: loki
    scrape_interval: 10s
    static_configs:
      - targets: [loki:3100]

  - job_name: tempo
    scrape_interval: 10s
    static_configs:
      - targets: [tempo:3200]