{
 "title": "Saga-Flow, Top Level Endpoints RED",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_target)(increase(traces_spanmetrics_calls_total{http_target=~\"\\\\/hello|\\\\/observability\"}[1m]))*40",
     "legendFormat": "{{http_target}}"
    }
   ]
  },
  {
   "title": "Overall Error %age",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\"}[10m]))/sum(increase(traces_spanmetrics_calls_total{}[10m]))) * 100"
    }
   ]
  },
  {
   "title": "Error Percentages by Target",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (http_target)(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",http_target=~\"\\\\/hello|\\\\/observability\"}[10m])))/(sum by (http_target)(increase(traces_spanmetrics_calls_total{status_code!=\"\",http_target!=\"\\\\/hello|\\\\/observability\"}[10m]))) * 100",
     "legendFormat": "{{http_target}}"
    }
   ]
  },
  {
   "title": "Top 10 Highest Endpoint Latencies Over Last Minute",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_method,http_target)(increase(traces_spanmetrics_latency_sum{http_method=~\".+\", http_target=~\"\\\\/hello|\\\\/observability\"}[1m]) / increase(traces_spanmetrics_latency_count{http_method=~\".+\", http_target=~\"\\\\/hello|\\\\/observability\"}[1m])))*1000"
    }
   ]
  },
  {
   "title": "All Endpoint Latencies in ms (Last 10 mins)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "sum by (http_method,http_target)(increase(traces_spanmetrics_latency_sum{http_method=~\".+\", http_target=~\"\\\\/hello|\\\\/observability\"}[10m]) / increase(traces_spanmetrics_latency_count{http_method=~\".+\", http_target=~\"\\\\/hello|\\\\/observability\"}[10m]))*1000",
     "legendFormat": "{{http_target}} - {{http_method}}"
    }
   ]
  },
  {
   "title": "95th Percentile Response Latencies (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(http_target, le) (rate(traces_spanmetrics_latency_bucket{service=\"hello-observability\"}[15s])))",
     "legendFormat": "{{http_target}}"
    }
   ]
  }
 ]
}